execute pathogen#infect()
syntax on
autocmd VimEnter * NERDTree
:set mouse=a
:set number
:set t_Co=256
:let g:airline_theme='base16'
:let g:indent_guides_enable_on_vim_startup = 1
:let g:NERDTreeWinSize=20
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=3
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=4
